export const FORMS = {

  /* =========================
     INVENTÁRIO DE EVITAÇÃO
  ========================= */
  YRAI: {
    key: "YRAI",
    title: "Inventário de Evitação (YRAI)",
    instructions:
      "Leia cada afirmação e marque o quanto ela descreve você usando a escala de 1 a 6.",

    scaleLabels: [
      "Completamente falso",
      "Falso na maioria das vezes",
      "Mais verdadeiro do que falso",
      "Moderadamente verdadeiro",
      "Verdadeiro na maioria das vezes",
      "Me descreve perfeitamente"
    ],

    groupSize: 20,

    items:[      
      [1,"Eu tento não pensar em coisas que me chateiam."],
      [2,"Eu tomo bebida alcoólica para me acalmar."],
      [3,"Eu me sinto feliz na maior parte do tempo."],
      [4,"Eu raramente me sinto triste ou para baixo."],
      [5,"Eu dou mais valor à razão do que à emoção."],
      [6,"Eu acredito que não deveria ficar bravo, nem com pessoas de quem eu não gosto."],
      [7,"Eu uso drogas para me sentir melhor."],
      [8,"Eu não sinto nada demais quando me lembro da minha infância."],
      [9,"Eu fumo quando estou chateado."],
      [10,"Eu sofro de problemas gastrointestinais (p. ex., má digestão, úlcera, colite)."],
      [11,"Eu me sinto dormente."],
      [12,"Eu frequentemente tenho dores de cabeça."],
      [13,"Eu me retraio quando fico bravo, fico mais fechado."],
      [14,"Eu não tenho tanta energia quanto a maioria das pessoas da minha idade."],
      [15,"Eu sofro de dores musculares."],
      [16,"Eu assisto muita TV quando estou sozinho."],
      [17,"Eu acredito que se deva usar a razão para manter as emoções sob controle."],
      [18,"Eu não consigo antipatizar com alguém de forma intensa."],
      [19,"A minha filosofia quando as coisas dão errado é deixá-las de lado o mais rápido possível e seguir em frente."],
      [20,"Eu me afasto quando me sinto triste."],
      [21,"Eu não lembro muito da minha infância."],
      [22,"Eu tiro sonecas ou durmo muito ao longo do dia."],
      [23,"Os momentos em que me sinto mais feliz são quando estou passeando ou viajando."],
      [24,"Me manter focado nas minhas tarefas me impede de ficar chateado."],
      [25,"Eu passo muito tempo sonhando acordado."],
      [26,"Quando eu estou chateado, como para me sentir melhor."],
      [27,"Eu tento não pensar sobre memórias dolorosas do meu passado."],
      [28,"Eu me sinto melhor quando me mantenho sempre ocupado, sem deixar muito tempo livre para pensar."],
      [29,"Eu tive uma infância muito feliz."],
      [30,"Eu me afasto quando estou triste."],
      [31,"As pessoas dizem que eu sou como um avestruz, com a minha cabeça debaixo da terra (ou seja, eu tenho a tendência de ignorar pensamentos desagradáveis)."],
      [32,"Eu tenho a tendência de não pensar sobre perdas e decepções."],
      [33,"Frequentemente eu não sinto nada, mesmo quando a situação justifica emoções fortes."],
      [34,"Eu tive sorte de ter pais tão bons."],
      [35,"Eu tento ficar emocionalmente neutro na maior parte do tempo."],
      [36,"Eu percebo que fico comprando coisas de que não preciso para melhorar meu humor."],
      [37,"Eu procuro não me colocar em situações difíceis para mim ou que me deixem desconfortável."],
      [38,"Eu fico doente fisicamente quando as coisas não vão bem para mim."],
      [39,"Quando as pessoas me deixaram ou morreram, eu não fiquei muito chateado."],
      [40,"O que os outros pensam de mim não me incomoda."]
    ]
  },

  /* =========================
   INVENTÁRIO DE COMPENSAÇÃO (YCI) — 48 itens
========================= */
YCI: {
  key: "YCI",
  title: "Inventário de Compensação (YCI)",
  instructions:
    "Leia cada afirmação e marque o quanto ela descreve você usando a escala de 1 a 6.",

  scaleLabels: [
    "Completamente falso sobre mim",
    "Em grande parte falso sobre mim",
    "Um pouco mais verdadeiro do que falso sobre mim",
    "Moderadamente verdadeiro sobre mim",
    "Em grande parte verdadeiro sobre mim",
    "Me descreve perfeitamente"
  ],

  groupSize: 24,

  items: [

    [1,"Eu desconto as minhas frustrações nos outros."],
    [2,"Muitas vezes eu culpo os outros quando as coisas dão errado."],
    [3,"Eu demonstro muita raiva quando as pessoas me decepcionam ou me traem."],
    [4,"Eu não consigo parar de sentir raiva até me vingar."],
    [5,"Quando eu sou criticado, fico na defensiva."],
    [6,"É importante que os outros admirem minhas realizações ou conquistas."],
    [7,"Para mim, é importante demonstrar o meu sucesso (p. ex., com carros caros, roupas, casa)."],
    [8,"Eu me esforço muito para ficar entre os melhores ou mais bem-sucedidos."],
    [9,"Eu considero importante ser popular (p. ex., fazer parte de um grupo seleto)."],
    [10,"Eu frequentemente tenho fantasias de sucesso, fama, riqueza, poder ou popularidade."],
    [11,"Eu gosto de ser o centro das atenções."],
    [12,"Eu flerto mais ou sou mais sedutor do que as pessoas em geral."],
    [13,"Eu dou muita importância à ordem na minha vida (p. ex., organização, estrutura, planejamento, rotina)."],
    [14,"Eu gasto muita energia tentando evitar que as coisas deem errado."],
    [15,"Eu penso muito antes de tomar decisões para que eu não cometa um erro."],
    [16,"Eu sou bastante controlador em relação às pessoas à minha volta."],
    [17,"Eu gosto de estar em posições nas quais eu tenha controle ou autoridade sobre as pessoas ao meu redor."],
    [18,"Eu não gosto que as pessoas deem palpites sobre a minha vida."],
    [19,"Para mim, é muito difícil ceder ou chegar num consenso."],
    [20,"Eu não gosto de ser dependente de ninguém."],
    [21,"Eu considero essencial que eu tome as minhas próprias decisões e seja independente."],
    [22,"Eu tenho dificuldade de me comprometer com uma pessoa ou me manter em uma relação estável."],
    [23,"Eu gosto de ser uma pessoa livre, de ter liberdade para fazer o que eu quiser."],
    [24,"Eu tenho dificuldade de me limitar a um emprego ou carreira; eu gosto de ter liberdade de escolha."],
    [25,"Eu geralmente coloco as minhas próprias necessidades na frente das dos outros."],
    [26,"Muitas vezes eu sou exigente com as outras pessoas — eu gosto que tudo seja exatamente como tem que ser."],
    [27,"Eu preciso cuidar de mim primeiro, assim como fazem as outras pessoas."],
    [28,"Para mim, é muito importante que o meu ambiente seja confortável (p. ex., temperatura, luz, móveis)."],
    [29,"Eu me considero uma pessoa rebelde; eu frequentemente vou contra a autoridade estabelecida."],
    [30,"Eu não gosto de regras e sinto satisfação quando as desrespeito."],
    [31,"Eu gosto de não ser convencional, mesmo que isso me faça ser pouco popular ou que eu não me encaixe por isso."],
    [32,"Eu não procuro sucesso seguindo os padrões da sociedade (ex., riqueza, realizações, popularidade)."],
    [33,"Eu sempre fui diferente; nunca fui atrás da maioria."],
    [34,"Eu sou uma pessoa muito reservada; não gosto que as pessoas saibam muito a respeito da minha vida particular ou dos meus sentimentos."],
    [35,"Eu tento sempre parecer forte para as outras pessoas, mesmo que me sinta vulnerável ou inseguro."],
    [36,"Às vezes eu sou muito possessivo e fico muito grudado com as pessoas que eu valorizo."],
    [37,"Eu frequentemente manipulo os outros para atingir meus objetivos."],
    [38,"Em vez de pedir o que eu quero diretamente, muitas vezes prefiro conseguir as coisas por meios indiretos."],
    [39,"Eu mantenho as pessoas à distância para que elas só vejam as partes de mim que eu quero que elas vejam."],
    [40,"Eu sou uma pessoa extremamente crítica."],
    [41,"Eu sinto que me pressiono demais para satisfazer os meus próprios padrões e responsabilidades."],
    [42,"Muitas vezes eu não tenho tato ou sou insensível ao me expressar."],
    [43,"Eu tento ser otimista o tempo todo; não me permito dar atenção aos aspectos negativos."],
    [44,"Eu acho que é importante parecer feliz, independentemente de como eu me sinta por dentro."],
    [45,"Várias vezes eu sinto inveja ou fico frustrado quando os outros são mais bem-sucedidos ou recebem mais atenção do que eu."],
    [46,"Eu irei até aonde for necessário para me certificar de que eu ganhe o que é meu por direito e que eu não seja enganado ou traído."],
    [47,"Eu busco maneiras de ser mais esperto do que os outros para que eles não tirem vantagem de mim ou me magoem."],
    [48,"Eu sei exatamente o que dizer ou fazer para que os outros gostem de mim (p. ex., elogiar, dizer aquilo que eles querem ouvir)."]

  ]
},

/* =========================
   QUESTIONÁRIO DE MODOS (YAMI / YM2) — 186 itens (texto fiel ao Correção.CSV)
========================= */
PM2: {
  key: "PM2",
  title: "Questionário de Modos (YAMI / YM2)",
  instructions:
    "Abaixo estão listadas frases que as pessoas podem usar para se descrever. Para cada item, por favor, classifique com que frequencia, você acreditou ou sentiu cada uma das frases durante o último mês, usando a escala de 6 pontos abaixo.",
  scaleLabels: [
    "Nunca ou quase nunca",
    "Raramente",
    "Ás vezes",
    "Muitas vezes",
    "Grande parte do tempo",
    "Quase o tempo todo"
  ],
  groupSize: 25,
  items: [
    [1, "Eu me sinto entendiado (a)."],
    [2, "Eu me sinto vazio (a)."],
    [3, "Eu me sinto anestesiado (a)."],
    [4, "Eu me sinto desinteressado (a)."],
    [5, "Eu me sinto insosso (a)."],
    [6, "Eu me sinto  no ar."],
    [7, "Não ligo para nada, nada importa para mim."],
    [8, "Eu me sinto indiferente."],
    [9, "Não sinto nada."],
    [10, "Eu me sinto fora de mim mesmo(a) ou arrancado(a) de mim mesmo(a)."],
    [11, "Não me sinto conectado(a) a outras pessoas."],
    [12, "Não quero me envolver com pessoas."],
    [13, "Eu me sinto distante das outras pessoas. "],
    [14, "Eu me sinto frio(a) em relação a outras pessoas."],
    [15, "Quero ficar sozinho(a)."],
    [16, "É melhor não me aproximar ou me sentir apegado(a) a outras pessoas. "],
    [17, "Não sei o que quero ou preciso."],
    [18, "Não quero sentir nada."],
    [19, "Se eu me permitir sentir emoções posso perder o controle."],
    [20, "É melhor não expressar minhas necessidades, sentimentos ou opiniões para os outros."],
    [21, "Tenho impulsos de me ferir (por ex., me cortar), assim não vou sentir emoções perturbadoras."],
    [22, "Estou com vontade de usar drogas ou álcool para anestesiar meus sentimentos."],
    [23, "Queria fazer alguma coisa excitante ou relaxante para evitar meus sentimentos (por ex., trabalhar, jogar cartas, comer, fazer compras, atividades sexuais, assistir TV)."],
    [24, "Não quero pensar em meus problemas porque eles me aborrecem."],
    [25, "Quero me distrair dos pensamentos e sentimentos perturbadores."],
    [26, "Eu me sinto solitário(a)."],
    [27, "Sinto que ninguém me ama."],
    [28, "Sinto que não sou digno(a) de ser amado."],
    [29, "Eu me sinto fundamentalmente inadequado(a), inútil ou cheio(a) de defeitos."],
    [30, "Eu me sinto fraco(a) e desamparado(a)."],
    [31, "Eu me sinto triste."],
    [32, "Eu me sinto perdido(a)."],
    [33, "Eu me sinto carente."],
    [34, "Eu me sinto desesperado(a)."],
    [35, "Eu me sinto deixado(a) de fora ou excluído(a)."],
    [36, "Eu me sinto sem esperanças."],
    [37, "Eu me sinto amedrontado(a), assustado(a) ou ansioso(a)."],
    [38, "Fico preocupado(a) que as pessoas me abandonem ou morram."],
    [39, "Fico preocupado(a) que as pessoas me magoem, abusem de mim ou me castiguem."],
    [40, "Tenho medo das pessoas. "],
    [41, "Queria ter alguém para me abraçar ou estar perto de mim."],
    [42, "Queria ter alguém com quem me sentisse conectado(a)."],
    [43, "Não tem ninguém que realmente me escute ou me entenda."],
    [44, "Fico preocupado(a) que alguma coisa ruim me aconteça."],
    [45, "Fico preocupado(a) que outras pessoas riam de mim ou me humilhem."],
    [46, "Preciso que outras pessoas restaurem minha confiança muitas vezes."],
    [47, "Queria ter alguém que me sustentasse ou me protegesse."],
    [48, "Eu me sinto envergonhado(a)."],
    [49, "Estou com raiva de mim mesmo(a)."],
    [50, "Eu sou uma pessoa ruim."],
    [51, "Não consigo me perdoar."],
    [52, "Estou com raiva de mim mesmo(a) por ser fraco(a)."],
    [53, "Tenho impulso de me castigar me ferindo (por ex., me cortando)."],
    [54, "Eu mereço ser castigado(a)."],
    [55, "Estou com vontade de castigar alguém por ter feito algo errado."],
    [56, "Estou com raiva de mim mesmo(a) por me sentir carente."],
    [57, "Nego qualquer prazer a mim mesmo, pois não mereço ter prazer."],
    [58, "Serei mau se expressar minhas necessidades, sentimentos ou opiniões para outras pessoas. "],
    [59, "Serei mau se ficar bravo(a) com outras pessoas."],
    [60, "É minha culpa quando algo de ruim acontece."],
    [61, "Minhas necessidades ou sentimentos são errados."],
    [62, "Não mereço solidariedade quando algo de ruim acontece comigo."],
    [63, "Eu me sinto culpado(a)."],
    [64, "Eu me odeio ou me desprezo."],
    [65, "Não me permito fazer coisas prazerosas que outras pessoas fazem, pois sou mau."],
    [66, "Sou egoísta."],
    [67, "Sou preguiçoso(a)."],
    [68, "Sou burro(a)."],
    [69, "Estou pensando nos erros que cometi e estou com raiva de mim mesmo(a)."],
    [70, "Existem pessoas que me magoaram, mas não consigo \"perdoar e esquecer\"."],
    [71, "Não importa porque cometi um erro; quando faço algo de errado, tenho que pagar o preço."],
    [72, "Fico aborrecido(a) quando acho que alguém \"livrou a cara\" muito facilmente."],
    [73, "Fico com raiva quando as pessoas ficam procurando desculpas ou culpam outras pessoas por seus problemas."],
    [74, "Estou furioso(a) com alguém."],
    [75, "Estou com raiva de alguém por me deixar sozinho(a) ou me abandonar."],
    [76, "Estou com vontade de bater em alguém ou feri-lo pelo que fez comigo."],
    [77, "Estou com raiva por alguém não estar me dando o amor, atenção e carinho que preciso."],
    [78, "Tenho muita raiva dentro de mim que tenho que liberar."],
    [79, "Fui traído(a) ou tratado(a) de maneira injusta."],
    [80, "Fico com raiva quando alguém me diz como devo me sentir ou me comportar. "],
    [81, "Estou com raiva porque as pessoas estão tentando tirar minha liberdade ou independência. "],
    [82, "Eu me sinto frustrado(a) por outras pessoas."],
    [83, "Estou com vontade de repreender pessoas por causa do jeito que me trataram."],
    [84, "Minha raiva parece fora de controle."],
    [85, "Sinto impulsos violentos contra outras pessoas que me magoaram."],
    [86, "Consigo expressar meus sentimentos espontaneamente quando isso é apropriado."],
    [87, "Eu me permito sentir o prazer da vida e das coisas boas para mim mesmo(a)."],
    [88, "Eu mereço coisas boas tanto quanto as outras pessoas. "],
    [89, "Eu aceito minhas próprias limitações e as limitações de outras pessoas sem sentir raiva ou ficar frustrado(a)."],
    [90, "Eu consigo resolver problemas de maneira racional sem deixar que minhas emoções me dominem."],
    [91, "Tenho bom controle das minhas emoções, inclusive da raiva."],
    [92, "Eu enfrento meus problemas em vez de evitá-los."],
    [93, "Eu consigo pedir às outras pessoas para satisfazer minhas necessidades."],
    [94, "Tenho o direito de expressar minhas opiniões."],
    [95, "Sou capaz de cuidar de mim mesmo(a). "],
    [96, "Eu consigo discutir meus sentimentos com outras pessoas."],
    [97, "Eu aceito ajuda quando não consigo resolver um problema."],
    [98, "Tenho relacionamentos saudáveis com amigos e outras pessoas que conheço."],
    [99, "Faço as coisas que gosto de fazer e não apenas as coisas que tenho que fazer."],
    [100, "Quando há problemas tento muito resolvê-los."],
    [101, "Sei quando expressar ou não as minhas emoções."],
    [102, "Eu reivindico o que preciso sem passar dos limites."],
    [103, "Na maior parte, gosto de mim e me aceito como sou."],
    [104, "Tenho uma boa noção de quem eu sou e do que preciso para me fazer feliz."],
    [105, "Eu consigo me defender quando me sinto criticado(a) injustamente ou quando abusam ou se aproveitam de mim."],
    [106, "Eu me certifico de que tanto as minhas necessidades como as necessidades das outras pessoas sejam levadas em conta quando tomo alguma decisão."],
    [107, "Tenho um bom equilíbrio entre cuidar das outras pessoas e ter minhas próprias necessidades satisfeitas."],
    [108, "Quando cometo erros, consigo me perdoar."],
    [109, "Não sinto uma necessidade forte de impressionar outras pessoas ou me esforçar para outras pessoas gostarem de mim."],
    [110, "Eu me sinto confortável expressando minhas emoções (por ex., chorar, sentir raiva, alegria) na medida em que é adequado para a situação."],
    [111, "Gosto de fazer as coisas bem, mas não exijo tanto de mim que não consiga relaxar ou me divertir."],
    [112, "Quando necessário, concluo tarefas chatas e rotineiras a fim de realizar coisas que valorizo."],
    [113, "Eu deixo outras pessoas fazerem do jeito delas ao invés de expressar minhas próprias necessidades."],
    [114, "Nos relacionamentos, deixo a outra pessoa ter o controle."],
    [115, "Eu tento muito agradar as outras pessoas para evitar conflito, confronto ou rejeição."],
    [116, "Eu dou mais aos outros do que recebo em troca."],
    [117, "Eu ajo de modo passivo, mesmo quando não gosto das coisas como elas são."],
    [118, "Eu fico tempo demais em situações que não são saudáveis para mim ou nas quais minhas necessidades não estão sendo satisfeitas."],
    [119, "Eu mudo dependendo das pessoas com quem estou, assim elas vão gostar de mim ou me aprovar."],
    [120, "Eu procuro outras pessoas para me ajudarem porque não confio no meu próprio julgamento ou decisões."],
    [121, "Permito que as outras pessoas me critiquem ou me coloquem para baixo."],
    [122, "Permaneço em relacionamentos com pessoas que são instáveis ou que não assumem compromisso comigo."],
    [123, "Acho difícil sair de relacionamentos nos quais estou sofrendo abuso ou sendo mal tratado(a). "],
    [124, "Em muitos dos meus relacionamentos importantes, não tenho muito amor, atenção, apoio ou empatia."],
    [125, "Faço muitas coisas com desleixo ou sem entusiasmo porque espero que elas deem errado ou que ficarei decepcionado(a)."],
    [126, "Estou tão preocupado(a) fazendo coisas para outras pessoas que não tenho muito tempo para mim mesmo(a)."],
    [127, "Deixo outras pessoas cuidarem de mim porque não me sinto capaz de enfrentar bem sozinho(a)."],
    [128, "Desconto minhas frustrações nas pessoas que estão ao meu redor."],
    [129, "Tenho a tendência de culpar os outros quando as coisas dão erradas."],
    [130, "Eu me esforço para que as outras pessoas me admirem por minhas realizações e conquistas."],
    [131, "Eu compro coisas para que os outros vejam que sou bem sucedido(a) (por ex., carros caros, roupas de marca, uma bela casa)."],
    [132, "É mais importante para mim ser o/a número 1 (por ex., o/a mais popular, o/a mais bem sucedido(a), o/a mais rico(a), o/a mais poderoso(a))."],
    [133, "Eu faço coisas para ser o centro das atenções."],
    [134, "Eu tento mais que a maioria das pessoas ter ordem em minha vida (por ex., organização, estrutura, planejamento, rotina)."],
    [135, "Sou bastante controlador(a) em relação às pessoas ao meu redor."],
    [136, "Eu não me deixo ser dependente de ninguém."],
    [137, "Eu normalmente coloco as minhas próprias necessidades antes dos outros."],
    [138, "Sou exigente com outras pessoas. "],
    [139, "Sou rebelde de muitas maneiras e vou contra a autoridade estabelecida."],
    [140, "Sinto que não deveria seguir as mesmas regras que as outras pessoas. "],
    [141, "Sou muito possessivo(a) ou ligado(a) às pessoas que valorizo."],
    [142, "Eu manipulo para atingir meus objetivos."],
    [143, "Procuro maneiras de ser mais esperto que as pessoas para que elas não se aproveitem de mim ou me magoem."],
    [144, "Faço o que quero, independentemente das necessidades e sentimentos de outras pessoas."],
    [145, "Critico bastante as outras pessoas."],
    [146, "Fico irritado quando as pessoas não fazem o que peço a elas para fazerem."],
    [147, "Eu me sinto especial, melhor do que a maioria das outras pessoas."],
    [148, "Eu afasto as pessoas se elas tentam se aproximar de mim ou se intrometer na minha vida."],
    [149, "Eu não me esforço a concluir tarefas chatas e rotineiras."],
    [150, "Eu ajo impulsivamente ou expresso emoções que criam problemas para mim ou magoam outras pessoas."],
    [151, "Se eu não consigo atingir um objetivo, fico facilmente frustrado(a) e desisto."],
    [152, "Depois que comecei a ficar com raiva muitas vezes não me controlo e perco a cabeça."],
    [153, "Eu faço repetidamente coisas que são prazerosas, mesmo quando sei que não me fazem bem (por ex., beber, fumar, usar drogas, comer demais, sexo, jogar cartas). "],
    [154, "Eu fico facilmente entediado(a) e perco o interesse nas coisas. "],
    [155, "Para mim é difícil conseguir me controlar."],
    [156, "Eu digo o que sinto, ou faço coisas impulsivamente, sem pensar nas consequências. "],
    [157, "Eu quebro as regras e acabo me arrependendo."],
    [158, "Eu entro em encrencas mais do que outras pessoas."],
    [159, "Eu me esforço para ser mais responsável do que a maioria das outras pessoas."],
    [160, "Não estou me permitindo relaxar ou me divertir até que termine de fazer tudo o que tenho que fazer."],
    [161, "Estou tentando dar o melhor de mim em tudo o que experimento."],
    [162, "Estou tentando não cometer erros, senão, vou me decepcionar comigo mesmo(a)."],
    [163, "Estou sacrificando o prazer, saúde ou felicidade, para satisfazer meus próprios padrões."],
    [164, "Meus relacionamentos estão sofrendo porque estou me pressionando muito."],
    [165, "Estou em constante pressão para conquistar e ter as coisas feitas."],
    [166, "Sou duro(a) comigo mesmo(a)."],
    [167, "Sei que existe um jeito \"certo\" e um jeito \"errado\" de fazer as coisas; estou tentando muito fazer as coisas do jeito certo ou então vou começar a me criticar."],
    [168, "Tenho um rígido código de ética e moral que estou dando duro para seguir."],
    [169, "Minha vida neste momento se resume a fazer as coisas acontecerem e fazê-las do meu jeito \"certo\"."],
    [170, "Eu me sinto levado(a) a realizar coisas."],
    [171, "Eu me sinto amado(a) e aceito(a)."],
    [172, "Eu me sinto satisfeito(a) e em paz."],
    [173, "Eu me sinto conectado(a) a outras pessoas."],
    [174, "Sinto que sou ouvido(a), compreendido(a) e validado(a)."],
    [175, "Eu me sinto espontâneo(a) e divertido(a)."],
    [176, "Eu me sinto otimista."],
    [177, "Sinto que sou basicamente uma pessoa boa."],
    [178, "Sinto que normalmente tenho sucesso naquilo que tenho a alcançar."],
    [179, "Tenho uma boa noção de quem eu sou e do que eu preciso e do que sinto."],
    [180, "Sinto que tenho bastante estabilidade e segurança em minha vida."],
    [181, "Sinto que eu me encaixo com outras pessoas."],
    [182, "Eu me sinto confiante de que consigo ter a maioria das minhas necessidades importantes satisfeitas."],
    [183, "Eu me sinto seguro(a)."],
    [184, "Sinto que normalmente tenho atenção suficiente das outras pessoas."],
    [185, "Confio na maioria das outras pessoas."],
    [186, "Sinto que consigo tomar boas decisões e exercitar o bom discernimento"]
  ]
},


};
